# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
variables:
  uiName : 'Language'
  uiBuild : '$(uiSource)/build'


pool:
  name: Default
  demands:
   - agent.name -equals MSI-WSL

steps:
- script: |
    npm i -g @angular/cli
    npm i --force
    ng build --configuration=production
  displayName: 'angular cli insall, npm install and build'

- task : CmdLine@2
  inputs:
    script: |
      cd build

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(uiName).tar.gz'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'